"""initial

Revision ID: 22b0d353dd47
Revises: 
Create Date: 2026-03-07 19:22:47.302301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b0d353dd47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datarooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datarooms_owner_uid'), 'datarooms', ['owner_uid'], unique=False)
    op.create_table('drive_tokens',
    sa.Column('user_uid', sa.String(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_uid')
    )
    op.create_table('dataroom_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataroom_id', sa.String(), nullable=False),
    sa.Column('user_uid', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name='valid_role'),
    sa.ForeignKeyConstraint(['dataroom_id'], ['datarooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataroom_members_dataroom_id'), 'dataroom_members', ['dataroom_id'], unique=False)
    op.create_index(op.f('ix_dataroom_members_user_uid'), 'dataroom_members', ['user_uid'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataroom_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataroom_id'], ['datarooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_dataroom_id'), 'folders', ['dataroom_id'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataroom_id', sa.String(), nullable=False),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('uploaded_by_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataroom_id'], ['datarooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_dataroom_id'), 'files', ['dataroom_id'], unique=False)
    op.create_index(op.f('ix_files_folder_id'), 'files', ['folder_id'], unique=False)
    op.create_table('share_links',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataroom_id', sa.String(), nullable=False),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('permissions', sa.String(), nullable=False),
    sa.Column('created_by_uid', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("permissions IN ('viewer', 'editor')", name='valid_permissions'),
    sa.ForeignKeyConstraint(['dataroom_id'], ['datarooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_share_links_dataroom_id'), 'share_links', ['dataroom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_dataroom_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_files_folder_id'), table_name='files')
    op.drop_index(op.f('ix_files_dataroom_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_dataroom_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_dataroom_members_user_uid'), table_name='dataroom_members')
    op.drop_index(op.f('ix_dataroom_members_dataroom_id'), table_name='dataroom_members')
    op.drop_table('dataroom_members')
    op.drop_table('drive_tokens')
    op.drop_index(op.f('ix_datarooms_owner_uid'), table_name='datarooms')
    op.drop_table('datarooms')
    # ### end Alembic commands ###
